import type { Category, Opportunity } from './types';

export const CATEGORIES: Category[] = [
  { id: 'nature',    label: 'Nature',         color: 'var(--tag-nature)'    },
  { id: 'animals',   label: 'Animals',        color: 'var(--tag-animals)'   },
  { id: 'kids',      label: 'Kids',           color: 'var(--tag-kids)'      },
  { id: 'food',      label: 'Food Security',  color: 'var(--tag-food)'      },
  { id: 'seniors',   label: 'Seniors',        color: 'var(--tag-seniors)'   },
  { id: 'arts',      label: 'Arts & Culture', color: 'var(--tag-arts)'      },
  { id: 'housing',   label: 'Housing',         color: 'var(--tag-housing)'   },
  { id: 'health',    label: 'Health',          color: 'var(--tag-health)'    },
  { id: 'cleanup',   label: 'Cleanup',         color: 'var(--tag-cleanup)'   },
  { id: 'civic',     label: 'Civic',           color: 'var(--tag-civic)'     },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-001',
    title: 'Trail Maintenance Volunteer',
    org: 'East Bay Regional Park District',
    tags: ['nature'],
    commitment: 'monthly',
    days: 'weekends',
    city: 'Oakland', state: 'CA', zip: '94601',
    lat: 37.8044, lng: -122.2712,
    duration: '4 hrs/month',
    description: 'Help maintain trails and remove invasive plants in the East Bay hills. Work alongside experienced rangers in a beautiful outdoor setting.',
    fullDescription: 'Join our trail crew for monthly maintenance days in the East Bay Regional Parks. Tasks include clearing brush, repairing drainage, removing invasive species, and improving trail surfaces. All tools and training provided. Great for outdoor enthusiasts who want to give back to the parks they love.',
    contactName: 'Maria Chen',
    contactRole: 'Volunteer Coordinator',
    contactEmail: 'mchen@ebparks.org',
    contactPhone: '(510) 555-0142',
    nextSteps: 'Email Maria to sign up for the next orientation session, held the first Saturday of each month at 8am at the Chabot trailhead.',
  },
  {
    id: 'opp-002',
    title: 'Animal Shelter Dog Walker',
    org: 'Oakland Animal Services',
    tags: ['animals'],
    commitment: 'weekly',
    days: 'either',
    city: 'Oakland', state: 'CA', zip: '94605',
    lat: 37.7749, lng: -122.2150,
    duration: '2 hrs/week',
    description: 'Walk dogs, socialize cats, and help shelter animals stay healthy and happy while they await their forever homes.',
    fullDescription: 'Our shelter animals need regular exercise and socialization to remain adoptable and mentally healthy. Volunteers walk dogs, play with cats, and provide loving attention. After a brief orientation, you\'ll be cleared to visit animals on your own schedule. We ask for a minimum 2-hour commitment per week for at least 3 months.',
    contactName: 'James Okafor',
    contactRole: 'Shelter Volunteer Manager',
    contactEmail: 'jokafor@oaklandanimalservices.org',
    contactPhone: '(510) 555-0287',
    nextSteps: 'Complete the online interest form on our website, then attend one of our Saturday orientation sessions at 9am.',
  },
  {
    id: 'opp-003',
    title: 'After-School Tutoring Mentor',
    org: 'Oakland Literacy Coalition',
    tags: ['kids'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'Oakland', state: 'CA', zip: '94607',
    lat: 37.8001, lng: -122.2875,
    duration: '3 hrs/week',
    description: 'Provide one-on-one tutoring to K-8 students struggling with reading and math in underserved Oakland schools.',
    fullDescription: 'The Oakland Literacy Coalition partners with local schools to provide after-school academic support. Volunteers are matched with 1-2 students each semester and meet with them weekly to work on reading comprehension, math skills, and study habits. No teaching experience required — just patience, enthusiasm, and commitment. Training and curriculum provided.',
    contactName: 'Priya Nair',
    contactRole: 'Program Director',
    contactEmail: 'pnair@oaklandliteracy.org',
    contactPhone: '(510) 555-0391',
    nextSteps: 'Fill out the volunteer application online and schedule a brief phone interview with Priya. Background check required.',
  },
  {
    id: 'opp-004',
    title: 'Food Bank Warehouse Sorter',
    org: 'Alameda County Community Food Bank',
    tags: ['food'],
    commitment: 'flexible',
    days: 'weekdays',
    city: 'Oakland', state: 'CA', zip: '94606',
    lat: 37.7893, lng: -122.2340,
    duration: '3 hrs/shift',
    description: 'Sort and pack donated food at our warehouse so it can be distributed to families in need across the county.',
    fullDescription: 'Volunteers at our Oakland warehouse help receive, inspect, sort, and repackage food donations for distribution to 300+ partner agencies across Alameda County. No experience required. Shifts available Monday through Friday, 9am-12pm and 1pm-4pm. Sign up for individual shifts or set up a recurring schedule. This is physical work — expect to be on your feet.',
    contactName: 'Sandra Torres',
    contactRole: 'Volunteer Services Coordinator',
    contactEmail: 'storres@accfb.org',
    contactPhone: '(510) 555-0456',
    nextSteps: 'Register on our volunteer portal at accfb.org/volunteer to browse and sign up for available shifts.',
  },
  {
    id: 'opp-005',
    title: 'Senior Companion Visitor',
    org: 'Meals on Wheels of Alameda County',
    tags: ['seniors', 'food'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'Berkeley', state: 'CA', zip: '94710',
    lat: 37.8716, lng: -122.2727,
    duration: '2 hrs/week',
    description: 'Deliver hot meals and provide friendly companionship to isolated seniors in Berkeley who cannot leave their homes.',
    fullDescription: 'Many of our senior clients look forward to their meal delivery as their primary human contact of the day. Volunteers drive a short route of 8-12 deliveries, typically taking about 90 minutes, then spend extra time chatting with clients who want company. Routes are available Monday through Friday. We provide all the meals; you just need a valid driver\'s license and a reliable vehicle.',
    contactName: 'Ellen Park',
    contactRole: 'Route Coordinator',
    contactEmail: 'epark@mowac.org',
    contactPhone: '(510) 555-0512',
    nextSteps: 'Call Ellen or email to get started. Orientation takes about 30 minutes and can be done any weekday morning.',
  },
  {
    id: 'opp-006',
    title: 'Mural Restoration Assistant',
    org: 'Berkeley Arts Center',
    tags: ['arts'],
    commitment: 'one-time',
    days: 'weekends',
    city: 'Berkeley', state: 'CA', zip: '94704',
    lat: 37.8695, lng: -122.2594,
    duration: '6 hrs (one Saturday)',
    description: 'Help restore a beloved community mural in downtown Berkeley. No art experience required — just enthusiasm and a willingness to get paint on your hands.',
    fullDescription: 'The Berkeley Arts Center is organizing a one-day volunteer event to restore the famous Gilman Street mural, which has faded after years of weather exposure. Lead artist Danielle Ortiz will direct volunteers in cleaning, priming, and repainting sections under her guidance. All supplies provided. Lunch included. This is a festive community event open to all skill levels.',
    contactName: 'Danielle Ortiz',
    contactRole: 'Lead Artist & Coordinator',
    contactEmail: 'dortiz@berkeleyartscenter.org',
    contactPhone: '(510) 555-0678',
    nextSteps: 'RSVP on our website event page. Space limited to 30 volunteers. Wear clothes you don\'t mind getting paint on.',
  },
  {
    id: 'opp-007',
    title: 'Neighborhood Cleanup Crew',
    org: 'SF Brightworks',
    tags: ['cleanup', 'nature'],
    commitment: 'monthly',
    days: 'weekends',
    city: 'San Francisco', state: 'CA', zip: '94103',
    lat: 37.7749, lng: -122.4194,
    duration: '3 hrs/month',
    description: 'Join monthly neighborhood cleanup events to collect litter, remove graffiti, and beautify public spaces across San Francisco.',
    fullDescription: 'SF Brightworks organizes monthly neighborhood cleanup events in various San Francisco districts. Volunteers collect trash, pull weeds, remove stickers and graffiti, and plant flowers in public planters. Each event covers a different neighborhood. All supplies provided. Events are family-friendly and a great way to meet your neighbors while making a tangible difference.',
    contactName: 'Kevin Walsh',
    contactRole: 'Events Coordinator',
    contactEmail: 'kwalsh@sfbrightworks.org',
    contactPhone: '(415) 555-0723',
    nextSteps: 'Subscribe to our newsletter at sfbrightworks.org to receive monthly event announcements and RSVP links.',
  },
  {
    id: 'opp-008',
    title: 'Marine Mammal Rescue Volunteer',
    org: 'The Marine Mammal Center',
    tags: ['animals', 'nature'],
    commitment: 'weekly',
    days: 'either',
    city: 'San Francisco', state: 'CA', zip: '94965',
    lat: 37.8324, lng: -122.4975,
    duration: '4 hrs/week',
    description: 'Help care for injured and sick seals, sea lions, and other marine mammals at our rescue and rehabilitation facility in the Marin Headlands.',
    fullDescription: 'The Marine Mammal Center rescues, rehabilitates, and releases marine mammals from Alaska to Baja California. Our volunteer program is the backbone of our operations. After a multi-session training program, volunteers assist with animal care, feeding, medical procedures, and beach patrols. This is a demanding but profoundly rewarding commitment. Minimum 1-year commitment preferred.',
    contactName: 'Sofia Reyes',
    contactRole: 'Volunteer Training Manager',
    contactEmail: 'sreyes@marinemammalcenter.org',
    contactPhone: '(415) 555-0831',
    nextSteps: 'Attend one of our monthly information sessions before applying. Sessions held the second Tuesday of each month at 6pm at our Sausalito facility.',
  },
  {
    id: 'opp-009',
    title: 'Youth Theater Arts Coach',
    org: 'City Arts & Lectures SF',
    tags: ['arts', 'kids'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'San Francisco', state: 'CA', zip: '94102',
    lat: 37.7793, lng: -122.4157,
    duration: '2 hrs/week',
    description: 'Lead weekly drama and creative expression workshops for youth ages 10-17 in the Tenderloin neighborhood.',
    fullDescription: 'Our after-school theater program gives young people in the Tenderloin a creative outlet and a safe space to develop confidence and self-expression. Volunteers lead 90-minute sessions covering improv exercises, scene work, voice projection, and physical movement. Previous theater or teaching experience preferred but not required. Training provided. Semester-long commitment (January-May or September-December).',
    contactName: 'Marcus Lee',
    contactRole: 'Youth Programs Manager',
    contactEmail: 'mlee@cityartslectures.org',
    contactPhone: '(415) 555-0944',
    nextSteps: 'Submit a volunteer interest form through our website and schedule an introductory call with Marcus.',
  },
  {
    id: 'opp-010',
    title: 'Community Garden Steward',
    org: 'SF Rec & Parks – Garden Program',
    tags: ['nature', 'food'],
    commitment: 'weekly',
    days: 'either',
    city: 'San Francisco', state: 'CA', zip: '94117',
    lat: 37.7694, lng: -122.4862,
    duration: '3 hrs/week',
    description: 'Tend a community garden plot in the Inner Sunset, grow fresh produce, and help organize workshops for neighborhood residents.',
    fullDescription: 'SF Rec & Parks operates over 40 community gardens across the city. Garden Stewards take on leadership roles at individual gardens — maintaining shared tools, organizing volunteer workdays, welcoming new plot holders, and growing communal crops donated to the SF Marin Food Bank. Stewards commit to 3 hours per week and serve a minimum 2-year term.',
    contactName: 'Linh Tran',
    contactRole: 'Community Gardens Coordinator',
    contactEmail: 'ltran@sfrecpark.org',
    contactPhone: '(415) 555-1021',
    nextSteps: 'Attend an open house at any of our active garden sites to meet current stewards. Dates listed at sfrecpark.org/gardens.',
  },
  {
    id: 'opp-011',
    title: 'Senior Tech Help Desk',
    org: 'OATS (Older Adults Technology Services)',
    tags: ['seniors'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'San Jose', state: 'CA', zip: '95112',
    lat: 37.3382, lng: -121.8863,
    duration: '2 hrs/week',
    description: 'Help seniors in San Jose learn to use smartphones, tablets, and video calling to stay connected with family and access services.',
    fullDescription: 'Digital literacy opens the world for older adults. Our volunteers work one-on-one or in small groups with seniors at community centers and libraries to teach practical tech skills — video calling, email, online banking, telehealth appointments, and more. Patience and clear communication are more important than technical expertise. All volunteers receive a brief training on adult learning techniques.',
    contactName: 'Robert Kim',
    contactRole: 'Program Coordinator',
    contactEmail: 'rkim@oats.org',
    contactPhone: '(408) 555-1138',
    nextSteps: 'Complete the online volunteer application and attend a 2-hour onboarding session held every other Thursday at 5pm.',
  },
  {
    id: 'opp-012',
    title: 'Weekend Food Pantry Assistant',
    org: 'Second Harvest of Silicon Valley',
    tags: ['food'],
    commitment: 'flexible',
    days: 'weekends',
    city: 'San Jose', state: 'CA', zip: '95128',
    lat: 37.3192, lng: -121.9358,
    duration: '3 hrs/shift',
    description: 'Staff weekend food distribution events at community sites across San Jose, helping families access fresh groceries.',
    fullDescription: 'Second Harvest distributes food to over 500,000 people every month across Santa Clara and San Mateo counties. Our weekend distribution events need volunteers to check in clients, organize food bags, manage lines, and assist with setup and breakdown. Shifts are 3 hours and very flexible — sign up for as many or as few as you like. Spanish speakers especially welcome.',
    contactName: 'Ana Gutierrez',
    contactRole: 'Volunteer Engagement Manager',
    contactEmail: 'agutierrez@shfb.org',
    contactPhone: '(408) 555-1245',
    nextSteps: 'Register at shfb.org/volunteer and use the shift calendar to sign up for weekend events near you.',
  },
  {
    id: 'opp-013',
    title: 'Children\'s Hospital Art Cart',
    org: 'UCSF Benioff Children\'s Hospital Oakland',
    tags: ['arts', 'kids', 'health'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'Oakland', state: 'CA', zip: '94609',
    lat: 37.8271, lng: -122.2530,
    duration: '3 hrs/week',
    description: 'Bring art supplies and creative projects to pediatric patients, providing a joyful distraction during hospital stays.',
    fullDescription: 'Our Art Cart volunteers visit patients in their rooms and common areas, offering art projects tailored to the child\'s age and condition. No art teaching background required — we provide all supplies and project ideas. Volunteers must commit to a regular weekly shift for a minimum of 6 months and complete hospital onboarding (background check, health screening, HIPAA training). Incredibly rewarding work.',
    contactName: 'Tamara Wilson',
    contactRole: 'Child Life Volunteer Coordinator',
    contactEmail: 'twilson@ucsfbenioff.org',
    contactPhone: '(510) 555-1352',
    nextSteps: 'Submit a volunteer inquiry through UCSF\'s volunteer portal. Allow 3-4 weeks for onboarding clearance.',
  },
  {
    id: 'opp-014',
    title: 'Homeless Outreach Street Team',
    org: 'Compass Family Services',
    tags: ['housing', 'food'],
    commitment: 'monthly',
    days: 'weekends',
    city: 'San Francisco', state: 'CA', zip: '94105',
    lat: 37.7856, lng: -122.3965,
    duration: '4 hrs/month',
    description: 'Join monthly street outreach walks to distribute food, hygiene kits, and service information to people experiencing homelessness in SoMa and the Tenderloin.',
    fullDescription: 'Our street team walks designated routes in San Francisco\'s most impacted neighborhoods, building trust with people experiencing homelessness and connecting them to housing, healthcare, and social services. Volunteers distribute food bags, hygiene kits, and resource cards. Training in trauma-informed communication provided at orientation. This work requires empathy, resilience, and a non-judgmental attitude.',
    contactName: 'David Hernandez',
    contactRole: 'Outreach Team Lead',
    contactEmail: 'dhernandez@compass-sf.org',
    contactPhone: '(415) 555-1467',
    nextSteps: 'Attend a virtual orientation (first Wednesday of the month, 6pm) before joining your first street team walk.',
  },
  {
    id: 'opp-015',
    title: 'Urban Forestry Tree Planter',
    org: 'Friends of the Urban Forest',
    tags: ['nature', 'cleanup'],
    commitment: 'one-time',
    days: 'weekends',
    city: 'San Francisco', state: 'CA', zip: '94110',
    lat: 37.7483, lng: -122.4153,
    duration: '4 hrs (one Saturday)',
    description: 'Plant trees along San Francisco streets with our expert arborists and help expand the city\'s urban canopy.',
    fullDescription: 'Friends of the Urban Forest hosts tree planting events nearly every weekend across different SF neighborhoods. Each planting requires about 20 volunteers to dig holes, install trees, and build water basins. Arborists are on-site to direct the work. It\'s physical but deeply satisfying — you\'ll be able to walk by those trees for decades and know you planted them. Great for individuals, couples, and small groups.',
    contactName: 'Claire Murphy',
    contactRole: 'Volunteer Events Manager',
    contactEmail: 'cmurphy@fuf.net',
    contactPhone: '(415) 555-1573',
    nextSteps: 'Browse upcoming plantings and RSVP at fuf.net/plantings. No commitment required — each event is standalone.',
  },
  {
    id: 'opp-016',
    title: 'Big Brothers Big Sisters Mentor',
    org: 'Big Brothers Big Sisters of the Bay Area',
    tags: ['kids'],
    commitment: 'monthly',
    days: 'either',
    city: 'San Jose', state: 'CA', zip: '95110',
    lat: 37.3359, lng: -121.8905,
    duration: '6 hrs/month',
    description: 'Be matched with a young person and spend regular one-on-one time doing activities you both enjoy. A transformative relationship for both of you.',
    fullDescription: 'As a Big, you commit to spending at least 6 hours per month with your Little — going to the park, cooking together, visiting museums, attending events, or just hanging out. The relationship is one-on-one and community-based (activities happen in the community, not our offices). Matches are carefully made based on shared interests. Minimum 1-year commitment required. Background check and interview process.',
    contactName: 'Jessica Park',
    contactRole: 'Match Support Manager',
    contactEmail: 'jpark@bbbsba.org',
    contactPhone: '(408) 555-1689',
    nextSteps: 'Start your application online at bbbsba.org/volunteer. The matching process takes 4-8 weeks.',
  },
  {
    id: 'opp-017',
    title: 'Cat Socializer & Foster',
    org: 'Peninsula Humane Society',
    tags: ['animals'],
    commitment: 'flexible',
    days: 'either',
    city: 'San Jose', state: 'CA', zip: '95125',
    lat: 37.2952, lng: -121.8880,
    duration: 'Flexible',
    description: 'Socialize shy cats at the shelter or open your home to foster cats and kittens, helping them thrive before adoption.',
    fullDescription: 'Many cats arrive at shelters frightened and under-socialized. Our cat socializers visit regularly to offer gentle handling, play, and positive experiences. Foster volunteers take cats home temporarily — usually 2-6 weeks — providing a quiet environment for recovery or socialization. Fostering is especially critical for bottle-fed kittens. All food, supplies, and vet care covered. Foster families needed year-round.',
    contactName: 'Rachel Nguyen',
    contactRole: 'Foster Program Coordinator',
    contactEmail: 'rnguyen@peninsulahumanesociety.org',
    contactPhone: '(650) 555-1792',
    nextSteps: 'Attend a free foster orientation at our San Mateo campus (held twice monthly) or apply online to begin the process.',
  },
  {
    id: 'opp-018',
    title: 'Coastal Habitat Restoration',
    org: 'Golden Gate National Parks Conservancy',
    tags: ['nature'],
    commitment: 'monthly',
    days: 'weekends',
    city: 'San Francisco', state: 'CA', zip: '94129',
    lat: 37.7990, lng: -122.4662,
    duration: '4 hrs/month',
    description: 'Restore native plant habitat in the Presidio and Marin Headlands by removing invasive species and planting native seedlings.',
    fullDescription: 'The Golden Gate National Recreation Area is home to rare and endangered plant communities. Our restoration crews work monthly to remove aggressive invasive plants and establish native species. Work takes place on the Presidio grounds and Marin Headlands. Rangers provide training and all tools. Volunteer crews are a mix of regulars and newcomers. Light hiking required — most sites are reached by trail.',
    contactName: 'Amy Yamamoto',
    contactRole: 'Stewardship Volunteer Coordinator',
    contactEmail: 'ayamamoto@parksconservancy.org',
    contactPhone: '(415) 555-1856',
    nextSteps: 'Sign up at parksconservancy.org/volunteer for an upcoming stewardship day. New volunteers welcome anytime — no advance training required.',
  },
  {
    id: 'opp-019',
    title: 'Meals & Conversation for Seniors',
    org: 'Catholic Charities of Seattle',
    tags: ['seniors'],
    commitment: 'weekly',
    days: 'weekdays',
    city: 'Seattle', state: 'WA', zip: '98122',
    lat: 47.6062, lng: -122.3321,
    duration: '2 hrs/week',
    description: 'Serve lunch and provide companionship at our senior day center in the Capitol Hill neighborhood of Seattle.',
    fullDescription: 'Our senior day center serves lunch to 40-60 seniors Monday through Friday. Volunteers help set tables, serve food, assist with cleanup, and most importantly, sit with seniors and provide genuine conversation and connection. Many of our clients live alone and look forward to this social time deeply. Great opportunity to hear life stories and make meaningful connections across generations.',
    contactName: 'Father Thomas Reilly',
    contactRole: 'Volunteer Liaison',
    contactEmail: 'treilly@ccsww.org',
    contactPhone: '(206) 555-1963',
    nextSteps: 'Email Father Thomas to schedule a visit day. Orientation is informal and takes about 20 minutes on your first day.',
  },
  {
    id: 'opp-020',
    title: 'Community Mural Project',
    org: 'Seattle Office of Arts & Culture',
    tags: ['arts'],
    commitment: 'one-time',
    days: 'weekends',
    city: 'Seattle', state: 'WA', zip: '98104',
    lat: 47.6035, lng: -122.3300,
    duration: '8 hrs (two Saturdays)',
    description: 'Collaborate with local artists and neighbors to paint a large public mural celebrating Seattle\'s diverse communities.',
    fullDescription: 'The Seattle Office of Arts & Culture is commissioning a new 80-foot mural on the South end of the Pike Place Market parking garage. Lead artist collective Bright Walls is organizing volunteer painting days over two consecutive Saturdays. All skill levels welcome — sections are designed for mixed-ability volunteers. This is a ticketed volunteer event and spots fill up fast. Lunch provided both days.',
    contactName: 'Naomi Foster',
    contactRole: 'Public Art Project Manager',
    contactEmail: 'nfoster@seattle.gov',
    contactPhone: '(206) 555-2074',
    nextSteps: 'Apply for volunteer spots through the Seattle Arts event page. Priority given to Seattle residents. Acceptance notifications sent 2 weeks before event.',
  },
  {
    id: 'opp-021',
    title: 'Refugee Family Welcome Team',
    org: 'International Rescue Committee – Seattle',
    tags: ['housing', 'food', 'kids'],
    commitment: 'flexible',
    days: 'weekdays',
    city: 'Seattle', state: 'WA', zip: '98144',
    lat: 47.5989, lng: -122.3018,
    duration: '2–4 hrs/week',
    description: 'Help newly arrived refugee families navigate their new community — grocery shopping, school enrollment, English practice, and more.',
    fullDescription: 'The IRC\'s Welcome Team model pairs volunteers with a newly arrived family for their first 90 days in Seattle. Volunteers help with critical practical tasks: navigating public transit, shopping for groceries, enrolling children in school, setting up bank accounts, and practicing English conversation. This is high-impact, deeply human work. Volunteers commit to 4-6 hours per week for 90 days and receive comprehensive orientation.',
    contactName: 'Hana Al-Rashid',
    contactRole: 'Welcome Team Coordinator',
    contactEmail: 'halrashid@rescue.org',
    contactPhone: '(206) 555-2187',
    nextSteps: 'Attend a Welcome Team information session (held monthly) or apply online at rescue.org/volunteer. Background check required.',
  },
  {
    id: 'opp-022',
    title: 'Animal Rescue Transport Driver',
    org: 'Oregon Humane Society',
    tags: ['animals'],
    commitment: 'flexible',
    days: 'weekends',
    city: 'Portland', state: 'OR', zip: '97217',
    lat: 45.5731, lng: -122.6669,
    duration: 'Per transport (2-4 hrs)',
    description: 'Drive rescued animals from shelters across the state to our Portland facility where they\'ll receive care and find new homes.',
    fullDescription: 'The Oregon Humane Society coordinates animal transports from rural and overcrowded shelters to our Portland campus, where more animals can be rehomed. Volunteer drivers pick up animals (usually dogs or cats in travel crates) from designated drop-off points and deliver them to our admissions team. You need a vehicle, valid license, and the ability to safely transport animals. Transports are typically weekend mornings.',
    contactName: 'Bill Larson',
    contactRole: 'Transport Volunteer Coordinator',
    contactEmail: 'blarson@oregonhumane.org',
    contactPhone: '(503) 555-2294',
    nextSteps: 'Fill out our transport volunteer application online. No formal orientation needed — first transport is guided by phone.',
  },
  {
    id: 'opp-023',
    title: 'Youth Environmental Educators',
    org: 'Portland Parks & Recreation',
    tags: ['nature', 'kids'],
    commitment: 'monthly',
    days: 'weekdays',
    city: 'Portland', state: 'OR', zip: '97209',
    lat: 45.5230, lng: -122.6819,
    duration: '3 hrs/month',
    description: 'Lead hands-on environmental education activities for elementary school students at Portland\'s urban parks and nature centers.',
    fullDescription: 'Portland Parks & Recreation\'s Urban Ecology program brings K-5 students to parks for hands-on science and nature education. Volunteer educators lead activities like stream macroinvertebrate sampling, bird identification, and plant ecology walks. Curriculum is provided and all activities are designed for non-scientists. Volunteers commit to one school visit per month during the school year (September-June). Training workshop held in September.',
    contactName: 'Greg Sawyer',
    contactRole: 'Urban Ecology Volunteer Coordinator',
    contactEmail: 'gsawyer@portlandoregon.gov',
    contactPhone: '(503) 555-2401',
    nextSteps: 'Email Greg in August to join the fall training cohort. Space limited to 20 new educators per year.',
  },
  {
    id: 'opp-024',
    title: 'Pop-Up Food Pantry Volunteer',
    org: 'Oregon Food Bank',
    tags: ['food'],
    commitment: 'one-time',
    days: 'weekends',
    city: 'Portland', state: 'OR', zip: '97214',
    lat: 45.5155, lng: -122.6562,
    duration: '3 hrs (single event)',
    description: 'Staff one of our Saturday pop-up pantry events in Southeast Portland, distributing fresh produce and staple foods to community members.',
    fullDescription: 'Oregon Food Bank\'s pop-up pantries bring food directly to high-need neighborhoods on a rotating schedule. Each pop-up needs 8-12 volunteers to unload the truck, set up stations, welcome and assist clients, and break down after the event. Shifts are 3 hours and each event is independent — sign up for one or many. One of the most direct ways you can fight hunger in Portland.',
    contactName: 'Carmen Ruiz',
    contactRole: 'Volunteer Engagement Coordinator',
    contactEmail: 'cruiz@oregonfoodbank.org',
    contactPhone: '(503) 555-2518',
    nextSteps: 'Register at oregonfoodbank.org/volunteer and select "Pop-Up Pantry" events in the Portland region. No pre-registration requirements.',
  },
  {
    id: 'opp-025',
    title: 'Adaptive Sports Day Volunteer',
    org: 'Disability Sports Northwest',
    tags: ['kids', 'seniors', 'health'],
    commitment: 'one-time',
    days: 'weekends',
    city: 'Seattle', state: 'WA', zip: '98133',
    lat: 47.7043, lng: -122.3370,
    duration: '5 hrs (one Saturday)',
    description: 'Support our quarterly adaptive sports day for people of all ages and abilities — from wheelchair basketball to seated yoga.',
    fullDescription: 'Disability Sports Northwest holds quarterly Adaptive Sports Days that bring together 100+ participants of all ages for a day of inclusive athletic activities. Volunteers assist coaches, help participants with equipment, cheer from the sidelines, and ensure everyone feels welcome. No sports experience needed — just a positive attitude and willingness to follow the lead of our professional adaptive sports staff. Volunteers must be 16 or older.',
    contactName: 'Laura Simmons',
    contactRole: 'Events & Volunteer Manager',
    contactEmail: 'lsimmons@disabilitysportsnw.org',
    contactPhone: '(206) 555-2625',
    nextSteps: 'Sign up through our website events calendar. A brief volunteer orientation is held at 8am on the day of the event.',
  },
  {
    id: 'opp-026',
    title: 'Election Poll Worker',
    org: 'King County Elections',
    tags: ['civic'],
    commitment: 'one-time',
    days: 'weekdays',
    city: 'Seattle', state: 'WA', zip: '98104',
    lat: 47.6062, lng: -122.3321,
    duration: '14 hrs (Election Day)',
    description: 'Serve your community as a paid poll worker on Election Day, helping voters cast their ballots and ensuring a smooth, fair election process.',
    fullDescription: 'Poll workers are the backbone of every election. You\'ll be assigned to a vote center where you\'ll check in voters, assist with accessible voting equipment, answer questions, and help maintain orderly operations. Training is provided and mandatory. Poll workers are compensated for their time. This is a nonpartisan role — you\'re there to help every eligible voter participate, regardless of their political views.',
    contactName: 'Elections Volunteer Office',
    contactRole: 'Poll Worker Program',
    contactEmail: 'elections.volunteers@kingcounty.gov',
    contactPhone: '(206) 555-3101',
    nextSteps: 'Apply online at kingcounty.gov/elections/pollworker. Applications open 3 months before each election. Training dates assigned after acceptance.',
  },
  {
    id: 'opp-027',
    title: 'Nonpartisan Voter Registration Drive',
    org: 'League of Women Voters – Bay Area',
    tags: ['civic'],
    commitment: 'flexible',
    days: 'either',
    city: 'Oakland', state: 'CA', zip: '94612',
    lat: 37.8044, lng: -122.2712,
    duration: '3–4 hrs/event',
    description: 'Staff voter registration tables at community events, libraries, and campuses to help eligible residents register and update their voter information.',
    fullDescription: 'The League of Women Voters has championed nonpartisan voter registration for over a century. Volunteers staff registration tables at farmers markets, community centers, colleges, and public events across the Bay Area. Your job is simple: help people register or verify their registration status, answer basic questions about the process, and hand out official materials. No advocacy for any candidate or party — ever. Training provided.',
    contactName: 'Diane Watkins',
    contactRole: 'Voter Services Chair',
    contactEmail: 'dwatkins@lwvbayarea.org',
    contactPhone: '(510) 555-3214',
    nextSteps: 'Email Diane or sign up through our website to be added to the volunteer list. You\'ll be notified of upcoming registration events in your area.',
  },
  {
    id: 'opp-028',
    title: 'Community Emergency Response Team (CERT)',
    org: 'SF Department of Emergency Management',
    tags: ['civic'],
    commitment: 'flexible',
    days: 'either',
    city: 'San Francisco', state: 'CA', zip: '94102',
    lat: 37.7793, lng: -122.4193,
    duration: 'Training + on-call',
    description: 'Complete free FEMA-certified disaster response training and join a neighborhood team ready to support your community in the event of an earthquake, fire, or other emergency.',
    fullDescription: 'CERT volunteers receive 20 hours of free training in disaster medical operations, fire safety, light search and rescue, and team organization. After completing training, you\'re part of a neighborhood emergency response network that activates when professional responders are overwhelmed. CERT members are not first responders — you work within your immediate neighborhood to assist neighbors until help arrives. Ongoing drills and refreshers keep skills sharp.',
    contactName: 'CERT Program Office',
    contactRole: 'SF Neighborhood Preparedness',
    contactEmail: 'cert@sfdem.org',
    contactPhone: '(415) 555-3327',
    nextSteps: 'Register for the next CERT training cohort at sfdem.org/cert. Cohorts run quarterly and fill quickly. No experience required.',
  },
  {
    id: 'opp-029',
    title: 'City Budget Community Liaison',
    org: 'Portland Office of Community & Civic Life',
    tags: ['civic'],
    commitment: 'monthly',
    days: 'weekdays',
    city: 'Portland', state: 'OR', zip: '97201',
    lat: 45.5231, lng: -122.6765,
    duration: '3 hrs/month',
    description: 'Represent your neighborhood at monthly city budget briefings and bring information back to your community, ensuring residents have a voice in how public money is spent.',
    fullDescription: 'Portland\'s participatory budgeting process relies on community liaisons to bridge the gap between City Hall and neighborhood residents. Volunteers attend monthly briefings with city budget staff, ask questions on behalf of their neighbors, and share findings at community meetings. No prior government experience needed — just an interest in how your city works and a commitment to keeping your neighbors informed. All political viewpoints welcomed equally.',
    contactName: 'Civic Engagement Office',
    contactRole: 'Community & Civic Life',
    contactEmail: 'civic@portlandoregon.gov',
    contactPhone: '(503) 555-3440',
    nextSteps: 'Submit an interest form at portland.gov/civic-life/volunteer. Liaisons are selected to represent geographic and demographic diversity across the city.',
  },
  {
    id: 'opp-030',
    title: 'Neighborhood Council Member',
    org: 'Los Angeles Department of Neighborhood Empowerment',
    tags: ['civic'],
    commitment: 'monthly',
    days: 'weekdays',
    city: 'San Jose', state: 'CA', zip: '95110',
    lat: 37.3382, lng: -121.8863,
    duration: '4–6 hrs/month',
    description: 'Serve on a local advisory council that gives residents a direct voice in city decisions affecting their neighborhood — zoning, public safety, parks, transportation, and more.',
    fullDescription: 'Neighborhood councils are officially recognized advisory bodies that connect residents to their local government. Members attend monthly meetings, form committees, respond to city agency requests for community input, and advocate for neighborhood needs. This is elected service at the most local level — anyone who lives, works, or has a community interest in the neighborhood is eligible. Councils are nonpartisan and welcoming of all residents regardless of political affiliation.',
    contactName: 'Neighborhood Empowerment Office',
    contactRole: 'Council Support Division',
    contactEmail: 'neighborhood.councils@sanjoseca.gov',
    contactPhone: '(408) 555-3553',
    nextSteps: 'Find your neighborhood council at sanjoseca.gov/neighborhoods and attend a meeting as a guest first. Elections for open seats are held annually.',
  },
];
